import { useMemo, useState } from 'react'
import { Images, Play, X } from 'lucide-react'
import type { Celebration } from '../types/celebrations'
import { MediaLightbox } from './MediaLightbox'
import { CelebrationWhatsAppCTA } from './CelebrationWhatsAppCTA'

export type GalleryItem = { id: string; type: 'image' | 'video'; url: string; thumbnailUrl: string | null; alt: string }

export function CelebrationGallery({ celebration, onClose }: { celebration: Celebration; onClose: () => void }) {
  const [heroPlaying, setHeroPlaying] = useState(false); const [lightboxIndex, setLightboxIndex] = useState<number | null>(null)
  const items = useMemo<GalleryItem[]>(() => { const seen = new Set<string>(); const list: GalleryItem[] = []; const add = (item: GalleryItem) => { if (!seen.has(item.url)) { seen.add(item.url); list.push(item) } }; if (celebration.coverUrl) add({ id: 'cover', type: 'image', url: celebration.coverUrl, thumbnailUrl: null, alt: `Portada de ${celebration.title}` }); for (const media of celebration.media) add({ id: media.id, type: media.type, url: media.url, thumbnailUrl: media.thumbnailUrl, alt: media.alt ?? celebration.title }); if (celebration.trailerUrl) add({ id: 'trailer', type: 'video', url: celebration.trailerUrl, thumbnailUrl: celebration.coverUrl, alt: `Trailer de ${celebration.title}` }); return list }, [celebration])
  const heroImage = celebration.coverUrl ?? celebration.media.find(media => media.type === 'image')?.url ?? null
  return <div className="celebration-gallery"><div className="modal-hero-media">{heroPlaying && celebration.trailerUrl ? <video src={celebration.trailerUrl} poster={heroImage ?? undefined} controls playsInline preload="metadata" autoPlay onEnded={() => setHeroPlaying(false)} aria-label={`Trailer de ${celebration.title}`}/> : heroImage ? <img src={heroImage} alt={`Portada de ${celebration.title}`}/> : <div className="modal-media-empty">MR FIESTA / MEDIA</div>}{celebration.trailerUrl && !heroPlaying && <button className="modal-play" onClick={() => setHeroPlaying(true)} aria-label="Reproducir trailer"><Play size={24} fill="currentColor"/></button>}<button className="modal-close-mobile" onClick={onClose} aria-label="Cerrar celebración"><X size={18}/></button></div><div className="modal-copy"><div><p className="modal-eyebrow">CELEBRACIÓN REAL / {celebration.district ?? 'LIMA'}</p><h2>{celebration.title}</h2><p className="modal-meta">{celebration.childName}{celebration.age ? ` · ${celebration.age} años` : ''}{celebration.theme ? ` · ${celebration.theme}` : ''}</p>{celebration.shortDescription && <p className="modal-description">{celebration.shortDescription}</p>}</div><CelebrationWhatsAppCTA title={celebration.title} variant="full" className="modal-cta"/></div><div className="modal-media-grid">{items.map((item, index) => <button className="modal-media-thumb" key={item.id} onClick={() => setLightboxIndex(index)} aria-label={`Abrir ${item.type === 'video' ? 'video' : 'imagen'} ${index + 1}`}><span>{item.type === 'video' ? <Play size={18} fill="currentColor"/> : <Images size={18}/>}</span>{item.type === 'image' ? <img src={item.thumbnailUrl ?? item.url} alt={item.alt} loading="lazy"/> : item.thumbnailUrl ? <img src={item.thumbnailUrl} alt={item.alt} loading="lazy"/> : <div className="modal-video-thumb"><Play size={22}/></div>}</button>)}</div>{lightboxIndex !== null && <MediaLightbox items={items} index={lightboxIndex} onClose={() => setLightboxIndex(null)} onChange={setLightboxIndex}/>}</div>
}
