import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ArrowLeft, ArrowUpRight, CalendarDays, Check, ChevronRight, CircleAlert, Edit3, LogOut, Plus, Save, ShieldCheck } from 'lucide-react'
import type { User } from '@supabase/supabase-js'
import { supabase, isSupabaseConfigured } from '../lib/supabase'
import { createCelebration, getAdminCelebrations, isCurrentUserAdmin, signInAdmin, signOutAdmin, unpublishCelebration, updateCelebration, type CelebrationInput } from '../data/adminCelebrationsRepository'
import type { Celebration } from '../types/celebrations'
import { MediaUploader } from './MediaUploader'

type FormState = { id?: string; child_name: string; age: string; title: string; event_date: string; district: string; venue: string; theme: string; short_description: string; long_description: string; featured: boolean; slug: string; published: boolean }
const emptyForm: FormState = { child_name: '', age: '', title: '', event_date: '', district: '', venue: '', theme: '', short_description: '', long_description: '', featured: false, slug: '', published: false }

function slugify(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80) }
function formFromCelebration(item: Celebration): FormState { return { id: item.id, child_name: item.childName, age: item.age?.toString() ?? '', title: item.title, event_date: item.eventDate ?? '', district: item.district ?? '', venue: item.venue ?? '', theme: item.theme ?? '', short_description: item.shortDescription ?? '', long_description: item.longDescription ?? '', featured: item.featured, slug: item.slug, published: item.published } }
function formPayload(form: FormState): CelebrationInput { return { slug: form.slug.trim(), child_name: form.child_name.trim(), age: form.age ? Number(form.age) : null, title: form.title.trim(), event_date: form.event_date || null, district: form.district.trim() || null, venue: form.venue.trim() || null, theme: form.theme.trim() || null, short_description: form.short_description.trim() || null, long_description: form.long_description.trim() || null, featured: form.featured } }

function StatusBadge({ published }: { published: boolean }) { return <span className={`status-badge ${published ? 'is-published' : ''}`}><span/>{published ? 'PUBLICADO' : 'BORRADOR'}</span> }

function AdminLogin({ onSuccess }: { onSuccess: (user: User) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setBusy(true); try { const result = await signInAdmin(email, password); if (result.error || !result.user) setError(result.error ?? 'No se pudo iniciar sesión.'); else onSuccess(result.user) } catch { setError('No se pudo iniciar sesión. Inténtalo nuevamente.') } finally { setBusy(false) } }
  return <main className="admin-login"><div className="login-orbit"/><div className="login-card"><div className="admin-brand"><span>MR</span> FIESTA <small>PRIVATE ACCESS</small></div><div className="login-heading"><p className="admin-eyebrow"><ShieldCheck size={14}/> MR FIESTA / ADMIN</p><h1>Bienvenido<br/><em>de vuelta.</em></h1><p>Gestiona las celebraciones que el mundo va a vivir.</p></div><form onSubmit={submit}><label>Email<input type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Contraseña<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <p className="form-error"><CircleAlert size={15}/>{error}</p>}<button className="admin-button primary" disabled={busy}>{busy ? 'VALIDANDO...' : 'INICIAR SESIÓN'}<ArrowUpRight size={16}/></button></form><p className="login-foot">Acceso restringido a administradores autorizados.</p></div></main>
}

function CelebrationForm({ initial, onBack, onSaved }: { initial?: Celebration; onBack: () => void; onSaved: (item: Celebration, message: string) => void }) {
  const [form, setForm] = useState<FormState>(() => initial ? formFromCelebration(initial) : emptyForm); const [savedItem, setSavedItem] = useState<Celebration | undefined>(initial); const [slugEdited, setSlugEdited] = useState(Boolean(initial)); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const setField = (key: keyof FormState, value: string | boolean) => setForm(previous => { const next = { ...previous, [key]: value }; if ((key === 'child_name' || key === 'age') && !slugEdited) next.slug = slugify(`${key === 'child_name' ? value : next.child_name}${key === 'age' ? ` ${value}` : next.age ? ` ${next.age}` : ''}`); return next })
  async function save(publish: boolean) { setError(''); if (!form.child_name.trim() || !form.title.trim() || !form.slug.trim()) { setError('Completa nombre, título y slug.'); return } if (publish && !form.event_date && !form.district.trim()) { setError('Para publicar agrega una fecha o un distrito.'); return } setBusy(true); try { const payload = formPayload(form); const item = form.id ? await updateCelebration(form.id, payload, publish) : await createCelebration(payload, publish); setForm(formFromCelebration(item)); onSaved(item, publish ? 'Celebración publicada' : 'Borrador guardado') } catch (caught) { const message = caught instanceof Error ? caught.message : ''; setError(message.includes('duplicate') || message.includes('unique') ? 'Ese slug ya existe. Elige otro.' : 'No se pudo guardar. Inténtalo nuevamente.') } finally { setBusy(false) } }
  return <section className="admin-section"><div className="admin-section-head"><button className="back-link" onClick={onBack}><ArrowLeft size={16}/> Celebraciones</button><div><p className="admin-eyebrow">{initial ? 'EDITAR CELEBRACIÓN' : 'NUEVA CELEBRACIÓN'}</p><h1>{initial ? initial.title : 'Crea el próximo momento.'}</h1></div></div><div className="form-layout"><form className="celebration-form" onSubmit={e => { e.preventDefault(); void save(false) }}><div className="form-block"><div className="form-block-title"><span>01</span><div><h2>La celebración</h2><p>La información que le da identidad.</p></div></div><div className="field-grid"><label>Nombre del niño/a<input value={form.child_name} onChange={e => setField('child_name', e.target.value)} required /></label><label>Edad<input type="number" min="0" max="120" value={form.age} onChange={e => setField('age', e.target.value)} /></label></div><label>Título<input value={form.title} onChange={e => setField('title', e.target.value)} required /></label><div className="field-grid"><label>Slug<input value={form.slug} onChange={e => { setSlugEdited(true); setField('slug', slugify(e.target.value)) }} required /><small>URL: /celebraciones/{form.slug || 'tu-slug'}</small></label><label>Fecha<input type="date" value={form.event_date} onChange={e => setField('event_date', e.target.value)} /></label></div><div className="field-grid"><label>Distrito<input value={form.district} onChange={e => setField('district', e.target.value)} /></label><label>Lugar<input value={form.venue} onChange={e => setField('venue', e.target.value)} /></label></div><label>Temática<input value={form.theme} onChange={e => setField('theme', e.target.value)} /></label><label>Descripción corta<textarea rows={3} value={form.short_description} onChange={e => setField('short_description', e.target.value)} /></label><label>Descripción larga<textarea rows={6} value={form.long_description} onChange={e => setField('long_description', e.target.value)} /></label></div><div className="form-block media-placeholder"><div className="form-block-title"><span>02</span><div><h2>Fotos y videos</h2><p>Subidas directas a R2 con progreso real.</p></div></div><MediaUploader celebration={savedItem} onUpdated={item => { setSavedItem(item); setForm(formFromCelebration(item)); onSaved(item, 'Media actualizada') }}/></div><div className="form-actions"><label className="checkbox"><input type="checkbox" checked={form.featured} onChange={e => setField('featured', e.target.checked)}/><span>Celebración destacada</span></label><div><button type="submit" className="admin-button secondary" disabled={busy}><Save size={15}/> GUARDAR BORRADOR</button><button type="button" className="admin-button primary" disabled={busy} onClick={() => void save(true)}><Check size={15}/> PUBLICAR CELEBRACIÓN</button></div></div>{error && <p className="form-error form-error-bottom"><CircleAlert size={15}/>{error}</p>}</form></div></section>
}

function AdminList({ items, onNew, onEdit, onUnpublish, busy }: { items: Celebration[]; onNew: () => void; onEdit: (item: Celebration) => void; onUnpublish: (item: Celebration) => void; busy: string | null }) { return <section className="admin-section"><div className="admin-section-head list-head"><div><p className="admin-eyebrow">MR FIESTA / ADMIN</p><h1>Celebraciones</h1><p className="section-lede">Contenido publicado y en preparación.</p></div><button className="admin-button primary" onClick={onNew}><Plus size={17}/> NUEVA CELEBRACIÓN</button></div><div className="celebration-list">{items.length === 0 ? <div className="empty-state">Todavía no hay celebraciones. Crea la primera.</div> : items.map(item => <article className="celebration-row" key={item.id}><div className="row-index">{String(items.indexOf(item) + 1).padStart(2, '0')}</div><div className="row-main"><h2>{item.title}</h2><p>{item.childName}{item.age ? ` · ${item.age} años` : ''} {item.district ? `· ${item.district}` : ''}</p></div><div className="row-date"><CalendarDays size={14}/>{item.eventDate ?? 'Sin fecha'}</div><StatusBadge published={item.published}/><div className="row-featured">{item.featured ? 'FEATURED' : ''}</div><button className="row-action" onClick={() => onEdit(item)} aria-label={`Editar ${item.title}`}><Edit3 size={16}/><ChevronRight size={14}/></button>{item.published && <button className="unpublish-link" disabled={busy === item.id} onClick={() => onUnpublish(item)}>{busy === item.id ? '...' : 'Pasar a borrador'}</button>}</article>)}</div></section> }

export default function AdminApp() {
  const [user, setUser] = useState<User | null>(null); const [admin, setAdmin] = useState(false); const [checking, setChecking] = useState(true); const [items, setItems] = useState<Celebration[]>([]); const [editing, setEditing] = useState<Celebration | undefined>(); const [creating, setCreating] = useState(false); const [toast, setToast] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState<string | null>(null)
  const pathLabel = useMemo(() => editing ? 'Editar' : creating ? 'Nueva' : 'Todas', [creating, editing])
  async function verify(nextUser: User | null) { setUser(nextUser); if (!nextUser) { setAdmin(false); setChecking(false); return } try { setAdmin(await isCurrentUserAdmin(nextUser.id)) } catch { setAdmin(false) } finally { setChecking(false) } }
  useEffect(() => { if (!isSupabaseConfigured || !supabase) { setChecking(false); return } void supabase.auth.getSession().then(({ data }) => verify(data.session?.user ?? null)); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { void verify(session?.user ?? null) }); return () => listener.subscription.unsubscribe() }, [])
  useEffect(() => { if (admin) void refresh() }, [admin])
  async function refresh() { try { setItems(await getAdminCelebrations()); setError('') } catch { setError('No se pudieron cargar las celebraciones.') } }
  async function logout() { try { await signOutAdmin(); setEditing(undefined); setCreating(false) } catch { setError('No se pudo cerrar sesión.') } }
  async function handleUnpublish(item: Celebration) { setBusy(item.id); try { const updated = await unpublishCelebration(item.id); setItems(list => list.map(current => current.id === updated.id ? updated : current)); setToast('Celebración pasada a borrador'); setTimeout(() => setToast(''), 2800) } catch { setError('No se pudo cambiar el estado.') } finally { setBusy(null) } }
  if (!isSupabaseConfigured) return <div className="admin-message"><CircleAlert size={22}/><h1>Admin no configurado</h1><p>Agrega las variables de Supabase para activar el acceso.</p></div>
  if (checking) return <div className="admin-message"><div className="loader"/><p>Comprobando acceso...</p></div>
  if (!user) return <AdminLogin onSuccess={verify}/>
  if (!admin) return <div className="admin-message"><CircleAlert size={22}/><h1>No tienes permisos de administración.</h1><p>Este usuario está autenticado, pero no está autorizado para acceder al panel.</p><button className="admin-button secondary" onClick={() => void logout()}><LogOut size={15}/> CERRAR SESIÓN</button></div>
  return <div className="admin-app"><header className="admin-topbar"><a className="admin-brand" href="../"><span>MR</span> FIESTA <small>ADMIN</small></a><div className="admin-user"><span>{user.email}</span><button onClick={() => void logout()}><LogOut size={15}/> CERRAR SESIÓN</button></div></header><main className="admin-main"><div className="admin-crumb"><span>MR FIESTA / ADMIN</span><ChevronRight size={13}/><span>{pathLabel}</span></div>{editing || creating ? <CelebrationForm initial={editing} onBack={() => { setEditing(undefined); setCreating(false) }} onSaved={(item, message) => { setEditing(item); setCreating(false); setItems(list => { const exists = list.some(current => current.id === item.id); return exists ? list.map(current => current.id === item.id ? item : current) : [item, ...list] }); setToast(message); setTimeout(() => setToast(''), 2800) }}/> : <AdminList items={items} onNew={() => { setCreating(true); setEditing(undefined) }} onEdit={item => { setEditing(item); setCreating(false) }} onUnpublish={handleUnpublish} busy={busy}/>}</main>{toast && <div className="admin-toast"><Check size={16}/>{toast}</div>}{error && <div className="admin-toast is-error"><CircleAlert size={16}/>{error}<button onClick={() => setError('')}>×</button></div>}</div>
}
