import { useEffect, useRef, useState } from 'react'
import { Camera, Check, CircleAlert, FlipHorizontal2, Mic, RotateCcw, Square, Video, X } from 'lucide-react'

type CaptureMode = 'photo' | 'video'
type CameraCaptureProps = { mode: CaptureMode; onCancel: () => void; onCaptured: (file: File) => void }
const maxSeconds = 90
const recorderFormats = ['video/mp4;codecs=h264,aac', 'video/mp4', 'video/webm;codecs=vp9,opus', 'video/webm;codecs=vp8,opus', 'video/webm']

function formatTime(seconds: number) { return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}` }
function supportedMimeType() { return recorderFormats.find(type => typeof MediaRecorder !== 'undefined' && MediaRecorder.isTypeSupported(type)) ?? '' }
function extensionFor(mimeType: string) { return mimeType.startsWith('video/mp4') ? 'mp4' : 'webm' }
function makeName(mode: CaptureMode, extension: string) { const stamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14); return `mrfiesta-capture-${mode}-${stamp}.${extension}` }

export function CameraCapture({ mode, onCancel, onCaptured }: CameraCaptureProps) {
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const recorderRef = useRef<MediaRecorder | null>(null); const chunksRef = useRef<Blob[]>([]); const timerRef = useRef<number | null>(null)
  const [facingMode, setFacingMode] = useState<'environment' | 'user'>('environment'); const [phase, setPhase] = useState<'loading' | 'live' | 'recording' | 'review'>('loading'); const [seconds, setSeconds] = useState(0); const [file, setFile] = useState<File | null>(null); const [previewUrl, setPreviewUrl] = useState(''); const [error, setError] = useState(''); const [cameraCount, setCameraCount] = useState(1)

  function stopTracks() { streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; if (videoRef.current) videoRef.current.srcObject = null }
  function clearTimer() { if (timerRef.current !== null) { window.clearInterval(timerRef.current); timerRef.current = null } }
  async function startCamera(nextFacing = facingMode) { setError(''); setPhase('loading'); stopTracks(); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: nextFacing } }, audio: mode === 'video' }); streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play() } const devices = await navigator.mediaDevices.enumerateDevices(); setCameraCount(devices.filter(device => device.kind === 'videoinput').length); setPhase('live') } catch { setError('No pudimos acceder a la cámara. Revisa los permisos del navegador.'); setPhase('live') } }
  useEffect(() => { void startCamera(); return () => { clearTimer(); if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop(); stopTracks(); if (previewUrl) URL.revokeObjectURL(previewUrl) } }, [])
  useEffect(() => { const handleVisibility = () => { if (document.hidden && phase === 'recording') stopRecording() }; document.addEventListener('visibilitychange', handleVisibility); return () => document.removeEventListener('visibilitychange', handleVisibility) }, [phase])
  function startRecording() { const mimeType = supportedMimeType(); if (!mimeType) { setError('Este navegador no ofrece un formato de video compatible.'); return } if (!streamRef.current) return; chunksRef.current = []; const recorder = new MediaRecorder(streamRef.current, { mimeType }); recorderRef.current = recorder; recorder.ondataavailable = event => { if (event.data.size > 0) chunksRef.current.push(event.data) }; recorder.onstop = () => { const blob = new Blob(chunksRef.current, { type: mimeType }); const nextFile = new File([blob], makeName('video', extensionFor(mimeType)), { type: mimeType }); setFile(nextFile); setPreviewUrl(URL.createObjectURL(blob)); setPhase('review'); clearTimer(); stopTracks() }; recorder.start(); setSeconds(0); setPhase('recording'); timerRef.current = window.setInterval(() => setSeconds(current => { const next = current + 1; if (next >= maxSeconds) stopRecording(); return next }), 1000) }
  function stopRecording() { if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop(); clearTimer() }
  function capturePhoto() { const video = videoRef.current; if (!video || !video.videoWidth || !video.videoHeight) return; const canvas = document.createElement('canvas'); const scale = Math.min(1, 1920 / video.videoWidth); canvas.width = Math.round(video.videoWidth * scale); canvas.height = Math.round(video.videoHeight * scale); const context = canvas.getContext('2d'); if (!context) return; context.drawImage(video, 0, 0, canvas.width, canvas.height); canvas.toBlob(blob => { if (!blob) return; const nextFile = new File([blob], makeName('photo', 'jpg'), { type: 'image/jpeg' }); setFile(nextFile); setPreviewUrl(URL.createObjectURL(blob)); setPhase('review'); stopTracks() }, 'image/jpeg', .9) }
  function discard() { if (previewUrl) URL.revokeObjectURL(previewUrl); setPreviewUrl(''); setFile(null); void startCamera() }
  function close() { clearTimer(); if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop(); stopTracks(); onCancel() }
  function useCapture() { if (file) onCaptured(file) }
  const recordingWarning = seconds >= 75
  return <div className="capture-overlay" role="dialog" aria-modal="true" aria-label={mode === 'video' ? 'Grabar video' : 'Tomar foto'}><div className="capture-panel"><header className="capture-header"><div><span className="capture-kicker"><span className="capture-dot"/> MR FIESTA / CAPTURE</span><h2>{mode === 'video' ? 'Grabar video' : 'Tomar foto'}</h2></div><button className="capture-close" onClick={close} aria-label="Cerrar captura"><X size={20}/></button></header>{error ? <div className="capture-error"><CircleAlert size={18}/><p>{error}</p><button onClick={() => void startCamera()}>Reintentar</button></div> : phase === 'review' && previewUrl ? <div className="capture-review">{mode === 'video' ? <video src={previewUrl} controls playsInline/> : <img src={previewUrl} alt="Vista previa capturada"/>}<div className="capture-review-actions"><button className="capture-secondary" onClick={discard}><RotateCcw size={15}/> DESCARTAR</button><button className="capture-primary" onClick={useCapture}><Check size={15}/> USAR {mode === 'video' ? 'VIDEO' : 'FOTO'}</button></div></div> : <><div className="capture-viewfinder">{phase === 'loading' && <div className="capture-loading">Activando cámara...</div>}<video ref={videoRef} autoPlay muted playsInline/><span className="viewfinder-corner top-left"/><span className="viewfinder-corner top-right"/><span className="viewfinder-corner bottom-left"/><span className="viewfinder-corner bottom-right"/>{phase === 'recording' && <div className="recording-status"><span className="capture-dot"/> REC <b>{formatTime(seconds)} / 01:30</b></div>}</div>{recordingWarning && phase === 'recording' && <p className="capture-warning">Este video es pesado para la memoria del celular. Se detendrá en {maxSeconds - seconds}s.</p>}<div className="capture-controls">{cameraCount > 1 && <button className="camera-switch" onClick={() => { const next = facingMode === 'environment' ? 'user' : 'environment'; setFacingMode(next); void startCamera(next) }}><FlipHorizontal2 size={16}/> CAMBIAR CÁMARA</button>}{phase === 'recording' ? <button className="record-button stop" onClick={stopRecording}><Square size={18} fill="currentColor"/> DETENER</button> : <button className={`record-button ${mode === 'video' ? 'video' : 'photo'}`} onClick={mode === 'video' ? startRecording : capturePhoto}>{mode === 'video' ? <><Video size={19}/> REC</> : <><Camera size={19}/> CAPTURAR</>}</button>}{mode === 'video' && <span className="audio-note"><Mic size={13}/> Audio activado</span>}</div></>}</div></div>
}
